"""Scaffold check settings schema.

Generated by `python -m studio.shared.providers_common.scaffold`.
Rendered by the generic provider settings UI — do not hardcode fields in Vue.
"""


def settings_schema() -> dict:
    return {
        "type": "object",
        "properties": {
            "label_prefix": {
                'type': 'string',
                'label': 'Label prefix',
                'description': 'Optional prefix applied to generated output for identification.',
                'default': '',
                'ui': {'type': 'text'},
            },
        },
        "required": [],
    }
